SELECT O.OPERAREANAMESTR,
       COUNT(DISTINCT C.CUSTOMERID_PK) AS CUSTOMER_COUNT,
       COUNT(S.CUSTOMERID_PK) AS SUBSCRIBER_COUNT
  FROM CUSTOMEREN C
  JOIN SUBSCRIBEREN S ON C.CUSTOMERID_PK = S.CUSTOMERID_PK
  JOIN OPERAREAEN O ON O.OPERAREAID_PK = S.OPERAREAID
  JOIN BUSINESSEN B ON B.BUSINESSID_PK = S.BUSINESSID
  JOIN INSTANCEEN INC ON INC.SUBSCRIBERID_PK = S.SUBSCRIBERID_PK
  JOIN PRODUCTEN P ON INC.PRODUCTID = P.PRODUCTID_PK
 WHERE B.BUSINESSID_PK = 3
   AND INC.STATUSID = 0
   AND P.productchildtypeid = 1
 GROUP BY O.OPERAREANAMESTR;



